### ISSUE TITLE
L8 Got InvalidCastException

### ISSUE THREAD

**Issue by shinsenter** [grimzy/laravel-mysql-spatial#158]
I got an InvalidCastException for ‘point’ type with v5.0 and Laravel 8.

```
local.ERROR: Call to undefined cast [point] on column [coordinates] in model [App\Models\Location]. {"exception":"[object] (Illuminate\Database\Eloquent\InvalidCastException(code: 0): Call to undefined cast [point] on column [coordinates] in model [App\Models\Location]. at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:1108)
[stacktrace]
#0 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(557): Illuminate\Database\Eloquent\Model->isClassCastable('coordinate...')
#1 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(1501): Illuminate\Database\Eloquent\Model->castAttribute('coordinate...', Object(Grimzy\LaravelMysqlSpatial\Types\Point))
#2 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(394): Illuminate\Database\Eloquent\Model->transformModelValue('coordinate...', Object(Grimzy\LaravelMysqlSpatial\Types\Point))
#3 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(373): Illuminate\Database\Eloquent\Model->getAttributeValue('coordinate...')
#4 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1625): Illuminate\Database\Eloquent\Model->getAttribute('coordinate...')
```

**Comment by mesiarm** [comment]
Are you sure point cast is correct?
