### ISSUE TITLE
Geometry::fromWKB fails

### ISSUE THREAD

**Issue by deividaspetraitis** [grimzy/laravel-mysql-spatial#26]
Hello,

When decoding geometry data field from MySQL it fails for some reason with following exception:

```
"exception": "GeoIO\\WKB\\Parser\\Exception\\ParserException",
"message": "Parsing failed: Bad endian byte value 230.",
"trace": "#0 /home/vagrant/Code/xxx/public_html/vendor/grimzy/laravel-mysql-spatial/src/Types/Geometry.php(63): GeoIO\\WKB\\Parser\\Parser->parse('\\xE6\\x10\\x00\\x00\\x01\\x06\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x01\\x03...')\n#1 /home/vagrant/Code/xxx/public_html/vendor/grimzy/laravel-mysql-spatial/src/Eloquent/SpatialTrait.php(76): Grimzy\\LaravelMysqlSpatial\\Types\\Geometry::fromWKB('\\xE6\\x10\\x00\\x00\\x01\\x06\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x01\\x03...')\n#2 
```

This geometry contains `multipolygon`, have tested with geometry that contains `point` and worked fine.

Please see gist with all data required to reproduce issue:  https://gist.github.com/deividaspetraitis/1d685fa1cdab0ad5719a07c4162edb57

**Comment by deividaspetraitis** [comment]
Aright, mistery solved and seems that issue is not with this package rather with MySQL it self. I'm closing this issue. More details about reported bug: https://bugs.mysql.com/bug.php?id=88106
